# Generated by Django 5.1.1 on 2024-09-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskview',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
